# Generated by Django 4.1.3 on 2022-12-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('degree_tittle', models.CharField(max_length=300, verbose_name='Titulo Obtenido')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
            ],
            options={
                'verbose_name': 'Formacion',
                'verbose_name_plural': 'Formaciones',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='skills', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
            ],
            options={
                'verbose_name': 'Conocimiento',
                'verbose_name_plural': 'Conocimientos',
            },
        ),
    ]
